// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           int64       `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	SessionToken string      `json:"session_token"`
	CsrfToken    string      `json:"csrf_token"`
	UserAgent    string      `json:"user_agent"`
	Ip           string      `json:"ip"`
	CreatedAt    time.Time   `json:"created_at"`
	ExpiresAt    time.Time   `json:"expires_at"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

type Tenant struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Domain    string             `json:"domain"`
	Subdomain pgtype.Text        `json:"subdomain"`
	ApiKey    string             `json:"api_key"`
	Settings  []byte             `json:"settings"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	OtpCode      pgtype.Text        `json:"otp_code"`
	OtpExpiresAt pgtype.Timestamptz `json:"otp_expires_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
}
